# Generated by Django 3.1.5 on 2021-01-26 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("STARTED", "Started"),
                            ("PROCESSED", "Processed"),
                            ("COMPLETED", "Completed"),
                            ("ERROR", "Error"),
                        ],
                        max_length=50,
                    ),
                ),
                ("body", models.TextField()),
                ("detail", models.TextField()),
            ],
        ),
    ]
